"""hash password

Revision ID: c173a79890b6
Revises: 9f2bf92948fc
Create Date: 2022-08-14 19:07:32.278434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c173a79890b6'
down_revision = '9f2bf92948fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')
        batch_op.drop_column('password_hash_algorithm')
        batch_op.drop_column('password_salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_salt', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_hash_algorithm', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
