"""remove salt and hash algo

Revision ID: e15b394701aa
Revises: dea50ec2fbd2
Create Date: 2022-08-14 18:22:20.457786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15b394701aa'
down_revision = 'dea50ec2fbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('user', 'password_salt')
    op.drop_column('user', 'password')
    op.drop_column('user', 'password_hash_algorithm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash_algorithm', sa.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('password_salt', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
